### ISSUE TITLE
Tests Fail starting 2 Flow for Single Router

### ISSUE THREAD

**Issue by lalkrishna** [essentialdevelopercom/quiz-app#10]
I just changed the code to:

```
public func startGame<Question, Answer: Equatable, R: Router>(questions: [Question], router: R, correctAnswers: [Question: Answer]) -> Game<Question, Answer, R> {
    let flow = Flow(questions: questions, router: router, scoring: { scoring($0, correctAnswers: correctAnswers) })
    let dd = Flow(questions: questions, router: router) { answers  -> Int in
        return scoring(answers, correctAnswers: correctAnswers)
    }
    dd.start()
    flow.start()
    return Game(flow: dd)
}
```

And the test fails on `router.routedResult`. Why this happen?

**Comment by caiozullo** [comment]
Hi @lalkrishna. 

The test fails because you're creating and starting two game flows _with the same router_. Starting a flow has side-effects in the router collaborator, as the flow sends messages for the router to coordinate/handle the flow of questions and answers. 

This double-messaging to the router is unintended in the start method, so the tests are flagging it as a problem (which is good!).

What are you trying to achieve by creating two flows?
