### ISSUE TITLE
The Engine could do a better job of defining & enforcing invariants

### ISSUE THREAD

**Issue by michaellenaghan** [essentialdevelopercom/quiz-app#11]
The engine could do a better job of defining & enforcing invariants. For example, right now:

 * it's possible for correct answers to not be among the list of question options

 * it's possible for a single answer question to have multiple correct answers

 * it's possible for a multiple answer question to have only a single correct answer (that may or may not be OK, but I'm not sure it was intentional)

 * it's possible for a question to not have any correct answers at all

 * it's possible for correct answers to not have any questions at all

 * it's possible for the array of questions and array of options to become "unsynchronized" (e.g., if a question is moved but its options aren't)

 * it's possible for the array of questions and array of options to have different counts

While invariants could be enforced through runtime checks during initialization, I think it would be better to define models that simply don't allow certain kinds of errors in the first place.

I also find the router implementation rather strange. The questions are effectively a queue, but rather than dequeuing you search for the current question and then advance to the next. That implementation actually imposes another invariant: the questions in the array must be unique; otherwise users will end up in a loop.

Thank you very much for putting together such a high quality series, and for so many other high quality videos; very much appreciated!

**Comment by caiozullo** [comment]
Hi @michaellenaghan!

You're right about better defining & enforcing invariants. We mentioned those problems in the series. The root cause is *Primitive Obsession* as we haven't defined a strong model layer yet.

But it's coming in future episodes!

Regarding the Router, we've replaced it with a Delegate in Season 2. Moreover, questions don't need to be unique because the `Flow` uses the index to navigate through the questions (forward and backward).

Thank you for the feedback and for contributing to the project. ✅

**Comment by michaellenaghan** [comment]
Ah, understood; I just finished season 1 this morning, and was going to start season 2 tonight.

Thanks again!
