### ISSUE TITLE
Logic for determination of correct/wrong answer(s)

### ISSUE THREAD

**Issue by mihaicris** [essentialdevelopercom/quiz-app#9]
I am not sure if this was the intended behaviour, but when giving the answers for Caio's nationalities there are the 3 options: `Portuguese`, `American`, `Brazilian`. 
Now, if you tap first `Portuguese` and then `Brazilian`, then the answer would be indicated as correct. But if you tap first `Brazilian`, then `Portuguese`, the answer would be indicated as wrong. 

I am not sure if the order was desired initially, I would have shown both aswers as correct. 

This is because you store the answers in an array (not a set) or you check the array equality and not the membership in a collection.

Other remark is related with the determination of the correct answer place in the code design.

File: `ResultsPresenter.swift` in `QuizApp/Presentation`:
```swift
private func formattedWrongAnswer(_ userAnswer: [String], _ correctAnswer: [String]) -> String? {
    return correctAnswer == userAnswer ? nil : formattedAnswer(userAnswer)
}
```

I am not sure if this logic should belong to the Presentation layer. I think it should be located in a higher level class / component, maybe even in the `Engine` module. The presentation layer should only be responsible for transforming the `Result` data structure in the desired shape for the user interface.

What do you think?

**Comment by caiozullo** [comment]
Hi @mihaicris you're right, the answer should be correct regardless of the order. Thanks for pointing it out! I believe the problem was introduced in this commit https://github.com/essentialdevelopercom/quiz-app/commit/19670e76a8e65b9dcdfac870050f3094fbddf6b9. We'll have a better look soon.

Regarding determining the correct answer for Presentation purposes, we also agree with you. The logic should not be in the Presentation layer. We mentioned it during the series `Season 1` (https://www.essentialdeveloper.com/professional-ios-engineering-season-1), and it was a trade-off we made until we create a "business logic" layer. The solution is coming soon in `Season 2`! ✅⛩

**Comment by mihaicris** [comment]
Great, looking forward to it! Thanks! 👍

**Comment by caiozullo** [comment]
Fixed in Season 3!
